name: Build C

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discordapp.com/api/webhooks/789459362649341973/bUer4pRvWONk3J49uWKLQtjdRO2EDbaxO_1ODYHwiAxngWwor6Y4XHhiAk_iTS4S0rY5
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build job for {{ EVENT_PAYLOAD.repository.full_name }} started.'

      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install Compiler
        run: sudo apt install gcc g++ make -y
        
      - name: Compile Project
        run: |
          gcc -Wall -Wextra -pedantic-errors main.c

      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: '.'
          extensions: 'c'
          clangFormatVersion: 11
          style: llvm
          inplace: True
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
